### ISSUE TITLE
Release Tag

### ISSUE THREAD

**Issue by benjaminlill** [ericthehacker/magento-themefallbackfix#3]
Could you tag the latest commit so that a specific version can be pulled in via composer instead of the last commit.

Thanks

**Comment by AydinHassan** [comment]
@ericthehacker Any news on this? Would be nice to not rely on `dev-master` :smile:

**Comment by ericthehacker** [comment]
@benjaminlill @AydinHassan 
Sorry about that -- I've been really busy. I've just tagged 1.0.0: https://github.com/ericthehacker/magento-themefallbackfix/releases/tag/v1.0.0 .

Thanks for keeping on me about that.
